INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('1','граммы','Редис','2000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('2','граммы','Огурцы','1100');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('3','граммы','Салат Латук','2000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('4','граммы','Лук зелёный','1500');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('5','граммы','Сметана','2000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('6','граммы','Помидоры','5400');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('7','граммы','Картофель','2000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('8','граммы','Сыр Фета','3000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('9','граммы','Сосиски говяжие','3500');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('10','граммы','Лимон','1500');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('11','граммы','Авокадо','3000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('12','граммы','Свекла','1000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('13','граммы','Сыр российский','4000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('14','граммы','Кальмары','2500');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('15','граммы','Телятина филе','5500');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('16','граммы','Масло подсолнечное рафинированное','5500');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('17','граммы','Масло подсолнечное нерафинированное','6500');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('18','граммы','Майонез','2000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('19','граммы','Специи Паприка','1000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('20','граммы','Специи Пелец чили','5500');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('21','граммы','Яйцо куриное','10000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('22','граммы','Специи Карри','1000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('23','граммы','Рис','5500');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('24','граммы','Чеснок','1520');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('25','граммы','Соль поваренная','2000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('26','граммы','Перец Болгарский','5500');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('27','граммы','Говядина мякоть','6000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('28','граммы','Сметана 25%','4800');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('29','граммы','Томат-паста','5000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('30','граммы','Маслины без косточек','3000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('31','граммы','Куриное филе','6500');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('32','граммы','Морковь','4200');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('33','граммы','Горошек консервированный','2000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('34','граммы','Салат Лола-Росса','5500');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('35','граммы','Огурцы солёные','3000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('36','граммы','Колбаса вареная Докторская','4000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('37','граммы','Зелень Петрушка','1000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('38','граммы','Лук Репчатый','1000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('39','граммы','Капуста белокачанная квашенная','6000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('40','граммы','Фасоль бобы','4000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('41','граммы','Сельдь среднесоленая','3600');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('42','граммы','Курица целая','10000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('43','граммы','Перец Чили','5000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('44','граммы','Зелень Укроп','4800');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('45','граммы','Капуста белокачанная','6400');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('46','граммы','Масло сливочное','7200');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('47','граммы','Говядина в специях','6000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('48','граммы','Вода питьевая','11000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('49','граммы','Куриная грудка запеченая','3600');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('50','граммы','Масло оливковое Extra Virgin','3850');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('51','граммы','Специи Пелец чёрный молотый','3500');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('52','литры','Сок апельсиновый','50');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('53','литры','Сок яблочный','50');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('54','литры','Сок грейпфрутовый','40');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('55','литры','Сок Мультивитамин','50');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('56','литры','Сок томатный','30');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('57','литры','Кока-кола','50');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('58','литры','Пепси-кола','50');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('59','литры','Спрайт','30');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('60','литры','Тоник','30');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('61','литры','Моршинская, б/г','100');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('62','литры','Моршинская, газ','100');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('63','литры','7-ап','30');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('64','банка','Ред-Булл','50');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('65','грамм','Сахар песок','10000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('66','грамм','Сахар рафинад','5000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('67','грамм','Сахарная пудра','1000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('68','грамм','Чай зеленый, вес','1000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('69','грамм','Чай черный, вес','1000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('70','грамм','Чай фруктовый, вес','3000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('71','пакетик','Чай зеленый','300');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('72','пакетик','Чай черный','200');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('73','пакетик','Чай фруктовый','400');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('74','грамм','Какао','1000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('75','грамм','Кофе','8000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('76','милилитры','Грей Гус','5000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('77','милилитры','Немиров Деликат','10000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('78','милилитры','Немиров Премиум','30000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('79','милилитры','Егермейстер','5000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('80','милилитры','Коньяк Шабо ВС','10000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('81','милилитры','Коньяк Шабо ВСОП','15000');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('82','литры','Пиво Жигули','100');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('83','литры','Пиво Будвайзер','100');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('84','бутылка','Шампанское ФБ п/сл','96');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('85','бутылка','Шампанское ФБ брют','96');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('86','бутылка','Шампанское ФБ брют','96');
INSERT INTO raw_material(id, measure_unit, name, threshold) VALUES ('87','грамм','Лайм','2000');